### ISSUE TITLE
Issues & verifications when creating reports 

### ISSUE THREAD

**Issue by jacobschultz** [jamf/scout-public#12]
Scout allows advanced reports to be created, viewed and edited for both computer and mobile devices. While they are saved as separate reports, the UI that they use is fundamentally the same. This means that bugs found in mobile device reports are likely found in computer reports as well. The database table that holds reports is called `reports` which holds general information about the reports, while `reports_line_items` stores information about each line item, in it's parent report. This table stores thing like the order in the report, criteria information, etc. 

We have identified several issues when creating reports that need to be fixed. All of the report client side code lives in `/app/js/scripts.js`. 

**Tasks:**
1. Verify that you are able to create reports with the number of conditions ranging from 1 - 6 and that the `reports` table and `reports_line_items` tables are populated with the correct information as expected. This includes parentheses, proper line item order, type, etc. 
2. Verify you are able to make multiple reports one after each other without refreshing the page. Verify the reporting UI and all fields resets itself after creating a new report. 
3. Verify you are able to create a Computer report and mobile device report immediately after and vice versa. 
4. If any of the above scenarios fail, fix them.
5. Provide documentation about the various reports that were tried during QA testing 

**PR Ready When:** 
1. All of the above scenarios work without issue including creating reports with multiple line items, a single line item, etc. 
2. Able to create multiple reports without refreshing the page. 
3. All of the above data is saved in the database correct.y.

**Comment by alex-stout** [comment]
I've gone through to fix these and it seems that #38 resolves this issue.

**Comment by jacobschultz** [comment]
Fixed as part of #38
