### ISSUE TITLE
Add ability to delete objects from GUI

### ISSUE THREAD

**Issue by et-j** [jamf/scout-public#34]
Deleting objects (computers and devices) from MySQL is a frequent troubleshooting step in Scout as the information will re-populate from the target Jamf Pro environment. Adding an ability to delete this record from Scout in the GUI would speed up this step and is not a dangerous / risky capability due to presence of essential data in managed Jamf Pro environments.

**Comment by jacobschultz** [comment]
Just merged this to master! You'll now see a new 'broom' icon on the servers page. This is supposed to represent 'cleaning up' the server. It looks like this feature already existed for individual devices - the trash bin icon in the devices tables. It will delete it from scout, not the jamf pro server, so I may change this icon.
